### ISSUE TITLE
Comparing maps

### ISSUE THREAD

**Issue by BartAdv** [jimpil/fudje#10]
Comparing relies on the `clojure.data/diff` and it should check both `only-in-a` and `only-in-b` returned values. Otherwise, the expectation map containing some `nil` values, happily accepts any other values for given key.

**Comment by jimpil** [comment]
I apologise for responding so late - somehow the email slipped me completely. The good news is that this was fixed literally a week after you reported this (https://github.com/jimpil/fudje/blob/master/src/clojure/fudje/core.clj#L21). Nonetheless, many thanks for spending the time and the effort to report it.
