### ISSUE TITLE
awesome library

### ISSUE THREAD

**Issue by hoebat** [jimpil/fudje#2]
I'm really tempted to switch... but there's a fair bit of code I have to change. Is there like a plugin that can automatically move all midje tests to fudge tests?

**Comment by jimpil** [comment]
Hello @zcaudate ,

Thank you for your kind words...
There do exist facilities (macros basically), to assist you automatically rewrite your midje tests. I recommend having a look at the "Migrating existing midje facts" section of the intro.md file.  In short, what you need to do is to replace midje.sweet  with fudje.sweet in the ns declaration. As soon as you do that, you're basically done with the midje dependency, and if the namespace compiles then chances are that the tests will pass as well. The things to watch out for are midje meta-constants + expressions like `let` and/or `binding` which have the potential of shadowing the mocks if they appear right under a `fact`. I really don't want to confuse you with this, so I 'll stop here...if you encounter problems feel free to poke me again and I'll be happy to help you migrate any midje test ...generally speaking, it's good to remember that fudje is syntactically stricter than midje (fudje `fact` expects assertions (expressions triplets) followed by mocks (also triplets)). Also, for some real examples feel free to look at the sweet_test.clj file.  Hope that helps... :)

**Comment by jimpil** [comment]
Ah sorry, i forgot to mention that before you swap `midje.sweet` for `fudje.sweet` you need to manually convert 'repeated  mocks' (repeated mocked functions under the `provided` symbol) to multi-mocks. There is more information in the stubbing & mocking section of the intro.md file. Hope that helps...

**Comment by hoebat** [comment]
thanks! I'm gunna give it serious shot in my next project.
