### ISSUE TITLE
 `novate.sweet/fact` requires a string description error

### ISSUE THREAD

**Issue by hoebat** [jimpil/fudje#4]
I'm trying to import hara to fudje... but some of my forms do not have a string descriptor

Assert failed: `novate.sweet/fact` requires a String description as the first arg (per `clojure.test/testing`)

is is possible to auto-generate a string if it is not there?

**Comment by jimpil** [comment]
Yes, this is indeed possible without too much trouble...I'll try to cut a relase with this in later this afternoon. Test description will default to the empty string if not provided.  Cheers :)

**Comment by hoebat** [comment]
thanks! I'm looking forward to it!

**Comment by jimpil** [comment]
0.9.4 addresses this :)
