### ISSUE TITLE
UnsupportedClassVersionError on jdk 1.7

### ISSUE THREAD

**Issue by hoebat** [jimpil/fudje#5]
I believe this has to do with the IChecker.class file being compiled on java 1.8:

Please see log:
https://travis-ci.org/zcaudate/vinyasa/builds/122154643

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: fudje/IChecker : Unsupported major.minor version 52.0, compiling:(fudje/util.clj:1:1)
```

**Comment by jimpil** [comment]
Hmmm I see... I just checked my IDEA's project structure and the JDK + project-level-language are set to 1.8. I think i can carry on using jdk 1.8, but i need at least to set the project-level-language to 1.7 or even 1.6. Would you happen have any extra recomendations/advice on this? Thanks in advance... :)

**Comment by hoebat** [comment]
I'm not really sure what to do either. Personally, I wouldn't bother with the IChecker interface. If you want java compatibility, you can provide an alternative way to build a checker.

**Comment by jimpil** [comment]
If you could try with 0.9.4 that'd be great! Thanks in advance...

**Comment by hoebat** [comment]
it's working now =)
