### ISSUE TITLE
Seemingly simple test failing due to metaconstant?

### ISSUE THREAD

**Issue by blueberry** [jimpil/fudje#7]
``` clojure
(facts
 "Problem 4.4"
 (- 1 (binomial-cdf 4 30/100 2)) => (roughly 0.0837))
```

This fails with: 
IllegalStateException Converting function-metaconstants is NOT supported as these tests will have to be re-written from scratch anyway!  fudje.util/metaconstant? (util.clj:18)

Problem is that fudje does not like the "-" (subtraction) sign. Why? It likes "+"...

**Comment by hoebat** [comment]
it fails for strings as well:

i.e, when there is  "--------" in the form

**Comment by jimpil** [comment]
oh wow... this is a major bug! what hapens is that if a function starts with `-` and ends with `-` then fudje assumes this is a funciton meta-constant.... I'll fix this tonight or early tomorrow morning. Thanks  guys :)

**Comment by blueberry** [comment]
Thank you. Should we expect the clojars release, or the bugfix will be available only in snapshots?

**Comment by jimpil** [comment]
0.9.5 fixes this, and the transformation is only applied to symbols. `clojure.core/-` has been special cased. I'm not super happy with this solution but I couldn't think of anything else to be honest :(.  any feedback and/or suggestions are welcome of course...
