### ISSUE TITLE
Roughly does not work for symbols

### ISSUE THREAD

**Issue by blueberry** [jimpil/fudje#8]
``` clojure
(let [n 41] 
 (facts  n => (roughly n)))
```

This works in midje, and is useful if I do not want to hardcode actual numbers that are used more than once in several tests. It does not in fudje. Is it intentional and what is a replacement for such use case?

**Comment by jimpil** [comment]
Ok this sounds like a bug as well...I'll have a look at it later this evening. Thanks a lot for reporting this :)

**Comment by jimpil** [comment]
0.9.5 fixes this :) Thanks again!
